### ISSUE TITLE
[Idea/Improvement] Multi platform support 

### ISSUE THREAD

**Issue by dguglielmi** [kodi-overlay/kodi-overlay#7]
We currently restrict building media-tv/kodi to only one platform at time. 

https://github.com/kodi-overlay/kodi-overlay/blob/e6e2f681d814c3379dca219be633b847831a7224/media-tv/kodi/kodi-21.0-r3.ebuild#L82

Some users might want to switch from X11, Wayland or GBM  at runtime.

We need to dig a little bit to see if multi-platform support can be considered.

Asked by mail by Andrzej P.

**Comment by dguglielmi** [comment]
Something like this

```
--- kodi-21.0-r3.ebuild	2024-06-05 21:47:57.632968310 +0200
+++ kodi-21.0-r3.ebuild	2024-06-05 21:47:53.220952815 +0200
@@ -79,7 +79,7 @@
 IUSE="airplay alsa bluetooth bluray caps cec +css dbus doc eventclients gbm gles lcms libusb lirc mariadb mysql nfs +optical pipewire pulseaudio samba soc +system-ffmpeg test udf udev upnp vaapi vdpau wayland webserver X +xslt zeroconf ${CPU_FLAGS}"
 REQUIRED_USE="
 	${PYTHON_REQUIRED_USE}
-	^^ ( gbm wayland X )
+	|| ( gbm wayland X )
 	?? ( mariadb mysql )
 	bluray? ( udf )
 	gbm? ( udev )
@@ -332,11 +332,17 @@
 }
 
 src_configure() {
+	local core_platform=(
+		$(usev gbm)
+		$(usev wayland)
+		$(usev X x11)
+	)
+
 	local mycmakeargs=(
 		-Wno-dev # less noise
 
 		-DAPP_RENDER_SYSTEM=$(usex gles gles gl)
-		-DCORE_PLATFORM_NAME=$(usev gbm)$(usev wayland)$(usev X x11)
+		-DCORE_PLATFORM_NAME="${core_platform[*]}"
 		-Ddocdir="${EPREFIX}/usr/share/doc/${PF}"
 		-DENABLE_TESTING=$(usex test)
 		-DVERBOSE=ON
```

**Comment by parona-source** [comment]
Now that I look it appears I was fooled by the binary names to think that only one could be enabled at once.

**Comment by dguglielmi** [comment]
This is building well on my system with IUSE="X gbm wayland"

Kodi automatically switch from X11 to wayland if we use an X11 or Wayland session. I can start a GBM session with a custom systemd unit files.

@parona-source : Can you have a look at this too ?

**Comment by dguglielmi** [comment]
> Now that I look it appears I was fooled by the binary names to think only could be enabled at once.

Same here, seems that when multi-platform is enabled the name of the binary is /usr/lib64/kodi/kodi.bin and Kodi switch the windowing system by himself. We can force it via --windowing=XX argument if needed. So I think we are "safe" if we relax the REQUIRED_USE with ||
